### ISSUE TITLE
CreateCredentialUnknownException: The incoming request cannot be validated

### ISSUE THREAD

**Issue by sereden** [Dashlane/android-passkey-example#2]
Hello! I would like to thank you for the example of the passkey that is quite hard to find!

When I'm trying to run the example it returns `CreateCredentialUnknownException: The incoming request cannot be validated` when I'm trying to store the user's passkey. I believe it's because the documentation doesn't cover steps that require developers to provide [support for Digital Asset Links](https://developer.android.com/training/sign-in/passkeys#add-support-dal). 
Also, the sample itself doesn't provide the `asset_statements` value in the strings. 
So, to be able to test the sample I refactored it to meet my hosted `assetlinks.json` configuration. However, the exception is still thrown.

According to the GIF in the repo description, I assume that you were able to reach an association between the app and your domain.
Since there is not much information about it on the Internet, could you please share your experience of the end-to-end implementation? Did you face the same exception? Is it required to be published on Play Store? Does the `credentialManager.createCredential` work immediately after `assetlinks.json` was published? Does it work when you host a JSON file on the subdomain and the app is configured to the subdomain (e.g. `dev.maindomain.com`)?

**Comment by GuillaumeBouxin** [comment]
Hey! Nice to know that it's useful. 🙂

We don't have any asset link for this application. I think your error is coming from somewhere else. I can perfectly use the application with the Android 14 beta 3 version. Maybe the problem is related to the passkey provider you're using to store the passkey. Which one are you using?

It's not clear to me if an association between an app and a website will be mandatory in the future, but for now, it's working fine without it.

**Comment by sereden** [comment]
@GuillaumeBouxin Thank you for your quick response! We are using Google Password Manager that is available by default

**Comment by sereden** [comment]
Okay, I've figured out how to change Google Password Manager with Dashlane, but the sample still doesn't work it asks to scan the QR.
One thing to mention, since custom passkey managers are available starting with Android 14 I run the sample against the emulator (linked to the real Google account, setup PIN and biometric). Any clues on how to make it work? :) 

![Screenshot_1686813196](https://github.com/Dashlane/android-passkey-example/assets/1812174/16b09c1c-04ee-42da-a4e3-c4b035d746f0)
![Screenshot_1686813199](https://github.com/Dashlane/android-passkey-example/assets/1812174/cb206893-e508-4906-8473-a7bcf1ef3af9)

**Comment by GuillaumeBouxin** [comment]
Today, you need to have the beta version of Dashlane to work with passkey, and go to "Settings," then "Password and Identity," and then select Dashlane in the list of "Passwords, passkeys, and data services."

**Comment by seusoul** [comment]
I also got the exception blow  when I'm trying to create the user's passkey.
"androidx.credentials.exceptions.CreateCredentialUnknownException: The incoming request cannot be validated"
I  am using Google Password Manager.
Is it work on your device when using Google Password Manager?
