### ISSUE TITLE
Keystore file missing

### ISSUE THREAD

**Issue by mimi89999** [Dashlane/android-passkey-example#4]
Hello,
https://github.com/Dashlane/android-passkey-example/blob/main/keystore.properties#L4 references a keystore file `debug.keystore`, but that file is not available on user machines. Normally it would be best to just use the default keystore that the user has configured, however for the app to actually be usable, it seems that it needs to be signed by the key with the fingerprint specified in `https://dashlane-passkey-demo.glitch.me/.well-known/assetlinks.json`.

**Comment by gbouxin-dashlane** [comment]
You are right, the keystore should be inside the repo. It's added now 👍
